pipeline {
    agent any

    environment {
        ANDROID_HOME = "/home/ridham/Android/Sdk"
        PATH = "/usr/bin/node:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"
    }

    stages {
        stage('Setup') {
            steps {
                 script {
                    // Set up Node.js
                    env.PATH = "/usr/share/man/man1/nodejs.1.gz:${PATH}"
                }
                // Use sudo to install necessary packages
                sh 'sudo npm install -g appium'
                sh 'sudo npm install -g appium-doctor'
                sh 'appium-doctor --android'
                sh 'pip install robotframework'
                sh 'pip install robotframework robotframework-appiumlibrary'
                sh 'sudo apt-get install android-tools-adb -y'
                sh  '. venv/bin/activate'
            }
        }
        stage('Start Appium Server') {
            steps {
                sh 'appium &'
                sleep 10 // Waiting for Appium server to start
            }
        }
        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && robot Tests/Calculator.robot'
            }
        }
    }

    post {
        always {
            // Clean up
            sh 'sudo pkill -f appium || true'
        }
        success {
            echo 'Tests passed!'
        }
        failure {
            echo 'Tests failed.'
        }
    }
}
